In [4]:
import numpy as np
#Create 1D, 2D, 3D arrays.
#1D Array
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],
             [4,5,6]])
arr3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print("1D Array:\n",arr1)
print("2D Array:\n",arr2)
print("3D Array:\n",arr3)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
#Perform addition, subtraction, multiplication, division.
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:\n",a+b)
print("Subtraction:\n",a-b)
print("Multiplication:\n",a*b)
print("Division:\n",a/b)

Addition:
 [5 7 9]
Subtraction:
 [-3 -3 -3]
Multiplication:
 [ 4 10 18]
Division:
 [0.25 0.4  0.5 ]


In [16]:
#Use functions: mean(), sum(), std(), reshape(), arange(), linspace().
print("Mean:",arr1.mean())
print("Sum:",arr1.sum())
print("Std:",arr1.std())
# reshape()
reshaped = np.arange(1, 10).reshape(3, 3)
print("Reshaped Array:\n", reshaped)

# arange()
range_array = np.arange(0, 10, 2)
print("Arange:", range_array)

# linspace()
line_array = np.linspace(0, 1, 5)
print("Linspace:", line_array)


Mean: 3.0
Sum: 15
Std: 1.4142135623730951
Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [17]:
#Find indices of max/min values.
print("Index of max value in arr1:",np.argmax(arr1))
print("Index of min value in arr1:",np.argmin(arr1))

Index of max value in arr1: 4
Index of min value in arr1: 0
